language: r

r_packages: 
    - MatrixEQTL

bioc_packages:
    - preprocessCore

r_binary_packages: 
    - testthat

r_github_packages:
    - jimhester/covr

notifications:
  webhooks: http://104.131.120.228:8080/hubot/travisci/general
  on_start: true

after_success:
  - Rscript -e 'covr::coveralls()'
